routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/','Website\HomeController@index')->name('home.index');
Route::get('/about-us','Website\HomeController@about')->name('about.us');
Route::get('/our-people','Website\HomeController@ourpeople')->name('our.people');
Route::get('/testimonial','Website\HomeController@testimonial')->name('testimonial');
Route::get('/faq','Website\HomeController@faq')->name('faq');
Route::get('/contact-us','Website\HomeController@contactus')->name('contact.us');

Route::get('/projects','Website\HomeController@projects')->name('projects');
Route::get('/project-detail/{name}/{id}','Website\HomeController@project_detail')->name('project.detail');
Route::get('/services','Website\HomeController@services')->name('services');
Route::get('/service-detail/{name}/{id}','Website\HomeController@service_detail')->name('service.detail');
Route::get('/news','Website\HomeController@news')->name('news');
Route::get('/news-detail','Website\HomeController@news_detail')->name('news.detail');

// products
Route::get('products','Website\HomeController@product_list')->name('products');
Route::get('products/{name}/{id}','Website\HomeController@product_bycat')->name('products.category');

Route::group(['middleware' => 'auth'], function(){
	// admin routes 
	Route::get('dashboard','Admin\DashboardController@index')->name('admin.dashboard');
	Route::resource('admin/home-image-slider','Admin\HomeImageSliderController');
	Route::resource('admin/offerforstudent','Admin\OfferForStudentController');
	Route::resource('admin/contactus','Admin\ContactUsController');
	Route::resource('admin/ourpresence','Admin\OurPresenceController');
	Route::resource('admin/awardsforyou','Admin\AwardsForYouController');
	Route::resource('admin/ourmindpower','Admin\OurMindPowerController');
	Route::resource('admin/ourpresence','Admin\OurPresenceController');
	Route::resource('admin/school','Admin\SchoolController');
	Route::resource('admin/testimonial','Admin\TestimonialController');
	Route::resource('admin/settings','Admin\WebsiteSettingController');
	Route::resource('admin/services','Admin\ServiceController');
	Route::resource('admin/service-detail','Admin\ServiceDetailController');
	Route::resource('admin/service-detail-image-slider','Admin\ServiceDetailImageSliderController');
	Route::resource('admin/what-we-make-us-different','Admin\WhatMakeUsDifferentController');
	Route::resource('admin/you-should-know','Admin\YouShouldKnowController');
	Route::resource('admin/projects','Admin\ProjectController');
	Route::resource('admin/project-detail','Admin\ProjectDetailController');
	Route::resource('admin/project-detail-image-slider','Admin\ProjectDetailImageSliderController');
	Route::resource('admin/faq','Admin\FAQController');
	Route::resource('admin/faq-detail','Admin\FAQDetailController');
	Route::resource('admin/aboutus','Admin\AboutusController');
	Route::resource('admin/aboutus-detail','Admin\AboutusDetailController');
	Route::resource('admin/what-we-do','Admin\WhatWeDoController');
	Route::resource('admin/what-we-do-detail','Admin\WhatWeDoDetailController');
	Route::resource('admin/our-team','Admin\OurTeamController');
	Route::resource('admin/general-info','Admin\GeneralInfoController');

	Route::resource('admin/seo-data','Admin\SeoDataController');

	Route::resource('admin/categories','Admin\CategoriesController');
	Route::resource('admin/products','Admin\ProductsController');

	Route::resource('admin/settings','Admin\SettingController');

});

app/Models/HomeImageSlider.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class HomeImageSlider extends Model
{
    protected $table = 'home_image_sliders';
 	protected $primaryKey = 'id';
}

app/Http/Controllers/Admin/HomeImageSliderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\HomeImageSlider;
use Illuminate\Support\Facades\Session;

class HomeImageSliderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $homes = HomeImageSlider::paginate('20');
        
        return view('admin.pages.home_image_slider.index',compact('homes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.pages.home_image_slider.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
                'image_name' => 'required',
                'heading_1' => 'required',
                'heading_2' => 'required',
                'heading_3' => 'required',
                'button_text' => 'required',
                'button_link' => 'required',
                'status' => 'required'
            ], [
                'image_name.required' => 'Title is required',
                'heading_1.required' => 'heading_1 is required',
                'heading_2.required' => 'heading 2 is required',
                'heading_3.required' => 'heading 3 is required',
                'button_text.required' => 'Button text is required',
                'button_link.required' => 'Button URl is required',
                'statue.required' => 'Status is required'
            ]);

        $homes = new HomeImageSlider();
        $homes->heading_1 = $request->heading_1;
        $homes->heading_2 = $request->heading_2;
        $homes->heading_3 = $request->heading_3;
        $homes->button_text = $request->button_text;
        $homes->button_link = $request->button_link;
        $homes->status = $request->status;
        $homes->slider_text_color = $request->slider_text_color;
        $homes->btn_bg_color = $request->btn_bg_color;
        
        if ($request->file('image_name')) {
            $image_name = $homes->image_name;
            $file = $request->image_name;
            $extension = $file->getClientOriginalExtension();
            $filename = $this->currentDatetimString(). '.' . $extension;
            $homes->image_name = $filename;
            $path = public_path('uploads/home_slider');
            $file->move($path, $filename);

            $file_path = public_path('uploads/home_slider' . DIRECTORY_SEPARATOR . $image_name);
            if (is_file($file_path)) {
                unlink($file_path);
            }

        }

        $homes->save();
        Session::flash('success','Record Save successfully !');
        return redirect()->route('home-image-slider.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $homes = HomeImageSlider::find($id);
        return view('admin.pages.home_image_slider.form',compact('homes'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
                'heading_1' => 'required',
                'heading_2' => 'required',
                'heading_3' => 'required',
                'button_text' => 'required',
                'button_link' => 'required',
                'status' => 'required'
            ], [
                'heading_1.required' => 'heading_1 is required',
                'heading_2.required' => 'heading 2 is required',
                'heading_3.required' => 'heading 3 is required',
                'button_text.required' => 'Button text is required',
                'button_link.required' => 'Button URl is required',
                'statue.required' => 'Status is required'
            ]);

        $homes = HomeImageSlider::find($id);
        $homes->heading_1 = $request->heading_1;
        $homes->heading_2 = $request->heading_2;
        $homes->heading_3 = $request->heading_3;
        $homes->button_text = $request->button_text;
        $homes->button_link = $request->button_link;
        $homes->status = $request->status;
        $homes->slider_text_color = $request->slider_text_color;
        $homes->btn_bg_color = $request->btn_bg_color;
         
        if ($request->file('image_name')) {
            $image_name = $homes->image_name;
            $file = $request->image_name;
            $extension = $file->getClientOriginalExtension();
            $filename = $this->currentDatetimString(). '.' . $extension;
            $homes->image_name = $filename;
            $path = public_path('uploads/home_slider');
            $file->move($path, $filename);

            $file_path = public_path('uploads/home_slider' . DIRECTORY_SEPARATOR . $image_name);
            if (is_file($file_path)) {
                unlink($file_path);
            }

        }

        $homes->save();
        Session::flash('success','Record Updated successfully !');

        return redirect()->route('home-image-slider.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $homes = HomeImageSlider::find($id);

        if(!is_null($homes)){
            $file_path = public_path('uploads/home_slider' . DIRECTORY_SEPARATOR . $homes->image);
            if (is_file($file_path)) {
                unlink($file_path);
            }
            $file_path = public_path('uploads/home_slider' . DIRECTORY_SEPARATOR . $homes->logo);
            if (is_file($file_path)) {
                unlink($file_path);
            }
        }
        $homes->delete();
        
        Session::flash('info','Record Delete successfully !');
        return back();
    }
}

resources/views/admin/pages/home_image_slider/includes/create-form.blade.php
<style type="text/css">
   .col-form-label {
    padding-top: calc(.375rem + 1px);
    padding-bottom: calc(.375rem + 1px);
    margin-bottom: 0;
    font-size: inherit;
    line-height: 1.5;
    display: block;
    width: 100%;
    text-align: left !important;
 }
</style>
<div class="right_col" role="main" style="min-height: 942px;">
   <div class="">
      <div class="page-title">
         <div class="title_left">
            <h3>Home Image Slider</h3>
         </div>
      </div>
      <div class="clearfix"></div>
      <div class="row">
         <div class="col-md-12 col-sm-12">
            <div class="x_panel">
               
               <div class="x_content">
                  @if(isset($homes) && !empty($homes))
                  
                  <form class="form-horizontal form-label-left" novalidate="" method="post" action="{{ route('home-image-slider.update',$homes->id) }}" enctype="multipart/form-data">
                     @method('PUT')
                  @else
                  <form class="form-horizontal form-label-left" novalidate="" method="post" action="{{ route('home-image-slider.store') }}" enctype="multipart/form-data">
                  
                  @endif
                     @csrf
                    
                     <span class="section">Home Image Slider </span>
                     <div class="col-md-6 col-sm-6">   
                        <div class="item form-group bad">
                        <label class="col-form-label label-align" for="name">Heading 1<span class="required">*</span>
                        </label>
                           <input id="heading_1" class="form-control" data-validate-length-range="6" data-validate-words="2" name="heading_1" placeholder="" required="" type="text" @if(isset($homes) && !empty($homes->heading_1)) value="{{ $homes->heading_1 }}" @endif>
                        @if ($errors->has('heading_1'))
                           <span class="text-danger">{{ $errors->first('heading_1') }}</span>
                        @endif
                     </div>
                  </div>

                     <div class="col-md-6 col-sm-6">
                     <div class="item form-group bad">
                        <label class="col-form-label label-align" for="email">Heading 2<span class="required">*</span>
                        </label>
                           <input type="text" id="heading_2" name="heading_2" required="" class="form-control" @if(isset($homes) && !empty($homes->heading_2)) value="{{ $homes->heading_2 }}" @endif>
                        @if ($errors->has('heading_2'))
                           <span class="text-danger">{{ $errors->first('heading_2') }}</span>
                        @endif
                     </div>
                  </div>
                  <div class="col-md-6 col-sm-6">
                     <div class="item form-group bad">
                        <label class="col-form-label label-align" for="email">Heading 3<span class="required">*</span>
                        </label>
                           <input type="text" id="heading_3" name="heading_3" required="" class="form-control" @if(isset($homes) && !empty($homes->heading_3)) value="{{ $homes->heading_3 }}" @endif>
                        @if ($errors->has('heading_3'))
                           <span class="text-danger">{{ $errors->first('heading_3') }}</span>
                        @endif
                     </div>
                  </div>
                  <div class="col-md-6 col-sm-6">
                     <div class="item form-group bad">
                        <label class="col-form-label label-align" for="email">
                           Image <span class="required">*</span> (1300px X 550px)
                        </label>
                           <input type="file" id="image_name" name="image_name" required="" class="form-control">
                        @if ($errors->has('image_name'))
                           <span class="text-danger">{{ $errors->first('image_name') }}</span>
                        @endif
                     </div>
                  </div>

                  <div class="col-md-6 col-sm-6">
                     <div class="item form-group bad">
                        <label class="col-form-label label-align" for="website">Button URl <span class="required">*</span>
                        </label>
                           <input type="url" id="button_link" name="button_link" required="" placeholder="" class="form-control" @if(isset($homes) && !empty($homes->button_link)) value="{{ $homes->button_link }}" @endif>
                        @if ($errors->has('button_link'))
                           <span class="text-danger">{{ $errors->first('button_link') }}</span>
                        @endif
                     </div>
                  </div>
                  <div class="col-md-6 col-sm-6">
                     <div class="item form-group">
                        <label class="col-form-label label-align" for="occupation">Button Text<span class="required">*</span>
                        </label>
                           <input id="occupation" type="text" name="button_text" class="optional form-control" @if(isset($homes) && !empty($homes->button_text)) value="{{ $homes->button_text }}" @endif>
                           @if ($errors->has('button_text'))
                              <span class="text-danger">{{ $errors->first('button_text') }}</span>
                           @endif
                     </div>
                  </div>
                  <div class="col-md-6 col-sm-6">
                     <div class="item form-group bad">
                        <label for="slider_text_color" class="col-form-label label-align">Slider Text Color</label>
                          <input type="color" id="slider_text_color" name="slider_text_color" value="#ff0000">
                     </div>
                  </div>
                  <div class="col-md-6 col-sm-6">
                     <div class="item form-group bad">
                        <label for="btn_bg_color" class="col-form-label label-align">Button Background Color</label>
                          <input type="color" id="btn_bg_color" name="btn_bg_color" value="#ffb600">
                     </div>
                  </div>
                  
                  <div class="col-md-6 col-sm-6">
                     <div class="item form-group bad">
                        <label for="password" class="col-form-label label-align">Status</label>
                           <select class="custom-select" name="status" id="status">
                              <option value="">Please select status</option>
                              <option value="1">Active</option>
                              <option value="0">Inactive</option>
                           </select>
                           @if ($errors->has('status'))
                              <span class="text-danger">{{ $errors->first('status') }}</span>
                           @endif
                     </div>
                  </div>

                     <div class="ln_solid"></div>
                     <div class="form-group">
                        <div class="col-md-6 offset-md-3">
                           <button type="submit" class="btn btn-primary">Cancel</button>
                           <button id="send" type="submit" class="btn btn-success">
                              @if(isset($homes) && !empty($homes)) Update @else Submit @endif
                           </button>
                        </div>
                     </div>
                  </form>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>

resources/views/admin/pages/home_image_slider/includes/table.blade.php
<div class="right_col" role="main" style="min-height: 674px;">
   <div class="">
      <div class="page-title">
         <div class="title_left">
            
         </div>
         <div class="title_right">
            <div class="col-md-5 col-sm-5   form-group pull-right top_search">
               <div class="input-group">
                 <a href="{{ route('home-image-slider.create') }}" class="btn btn-primary">Add New Record</a>
               </div>
            </div>
         </div>
      </div>
      <div class="clearfix"></div>
      <div class="row" style="display: block;">
  
         <div class="col-md-12 col-sm-12  ">
            <div class="x_panel">
               <div class="x_title">
                  <h2>Home Image Slider</h2>
                  <ul class="nav navbar-right panel_toolbox">
                     <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                     <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                         
                        </div>
                     </li>
                     <li><a class="close-link"><i class="fa fa-close"></i></a></li>
                  </ul>
                  <div class="clearfix"></div>
               </div>
               <div class="x_content">
               
                  <div class="table-responsive">
                     <table class="table table-striped jambo_table bulk_action">
                        <thead>
                           <tr class="headings">
                              <th>
                                #
                              </th>
                              <th>Heading 1 </th>
                              <th>Heading 2</th>
                              <th>Heading 3</th>
                              <th>Image </th>
                              <th>Button Text</th>
                              <th>Button URl </th>
                              <th><span class="nobr">Status</span></th>
                              <th>Text Color</th>
                              <th>Button Background Color</th>
                              <th>
                                 Action
                              </th>
                           </tr>
                        </thead>
                        <tbody>
                           @if(isset($homes) && !empty($homes))
                           @foreach($homes as $key => $value)
                           <tr class="even pointer">
                              <td class="a-center ">
                                 {{ ++$key }}
                              </td>
                              
                              <td> {{ $value->heading_1 }} </td>
                              <td> {{ $value->heading_2 }} </td>
                              <td> {{ $value->heading_3 }} </td>
                              <td>
                                 <img src="{{ asset('uploads/home_slider'.'/'.$value->image_name) }}" width="100px" height="100px">
                              </td>
                              <td>{{$value->button_text}}</td>
                              <td>{{$value->button_link}}</td>
                              <td>
                                 {{ $value->status == 1 ? 'Active' : 'Inactive'  }}
                              </td>
                              <td>{{$value->slider_text_color}}</td>
                              <td>{{$value->btn_bg_color}}</td>
                              <td>
                                 <a href="{{ route('home-image-slider.edit',$value->id) }}" class="btn btn-primary">Edit</a>
                                 <a class="delete btn btn-danger" href="javascript::void();" onclick="event.preventDefault();
                                                     document.getElementById('delete-homes-{{ $value->id }}').submit();">
                                                  Delete
                                 </a>
                                <form id="delete-homes-{{ $value->id }}" action="{{ route('home-image-slider.destroy',$value->id) }}" method="POST" style="display: none;">
                                 @method('delete')
                                        @csrf
                                </form>

                              </td>
                           </tr>
                           @endforeach
                           @endif
                        </tbody>
                     </table>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>