routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/','Website\HomeController@index')->name('home.index');
Route::get('/about-us','Website\HomeController@about')->name('about.us');
Route::get('/our-people','Website\HomeController@ourpeople')->name('our.people');
Route::get('/testimonial','Website\HomeController@testimonial')->name('testimonial');
Route::get('/faq','Website\HomeController@faq')->name('faq');
Route::get('/contact-us','Website\HomeController@contactus')->name('contact.us');

Route::get('/projects','Website\HomeController@projects')->name('projects');
Route::get('/project-detail/{name}/{id}','Website\HomeController@project_detail')->name('project.detail');
Route::get('/services','Website\HomeController@services')->name('services');
Route::get('/service-detail/{name}/{id}','Website\HomeController@service_detail')->name('service.detail');
Route::get('/news','Website\HomeController@news')->name('news');
Route::get('/news-detail','Website\HomeController@news_detail')->name('news.detail');

// products
Route::get('products','Website\HomeController@product_list')->name('products');
Route::get('products/{name}/{id}','Website\HomeController@product_bycat')->name('products.category');

Route::group(['middleware' => 'auth'], function(){
	// admin routes 
	Route::get('dashboard','Admin\DashboardController@index')->name('admin.dashboard');
	Route::resource('admin/home-image-slider','Admin\HomeImageSliderController');
	Route::resource('admin/offerforstudent','Admin\OfferForStudentController');
	Route::resource('admin/contactus','Admin\ContactUsController');
	Route::resource('admin/ourpresence','Admin\OurPresenceController');
	Route::resource('admin/awardsforyou','Admin\AwardsForYouController');
	Route::resource('admin/ourmindpower','Admin\OurMindPowerController');
	Route::resource('admin/ourpresence','Admin\OurPresenceController');
	Route::resource('admin/school','Admin\SchoolController');
	Route::resource('admin/testimonial','Admin\TestimonialController');
	Route::resource('admin/settings','Admin\WebsiteSettingController');
	Route::resource('admin/services','Admin\ServiceController');
	Route::resource('admin/service-detail','Admin\ServiceDetailController');
	Route::resource('admin/service-detail-image-slider','Admin\ServiceDetailImageSliderController');
	Route::resource('admin/what-we-make-us-different','Admin\WhatMakeUsDifferentController');
	Route::resource('admin/you-should-know','Admin\YouShouldKnowController');
	Route::resource('admin/projects','Admin\ProjectController');
	Route::resource('admin/project-detail','Admin\ProjectDetailController');
	Route::resource('admin/project-detail-image-slider','Admin\ProjectDetailImageSliderController');
	Route::resource('admin/faq','Admin\FAQController');
	Route::resource('admin/faq-detail','Admin\FAQDetailController');
	Route::resource('admin/aboutus','Admin\AboutusController');
	Route::resource('admin/aboutus-detail','Admin\AboutusDetailController');
	Route::resource('admin/what-we-do','Admin\WhatWeDoController');
	Route::resource('admin/what-we-do-detail','Admin\WhatWeDoDetailController');
	Route::resource('admin/our-team','Admin\OurTeamController');
	Route::resource('admin/general-info','Admin\GeneralInfoController');

	Route::resource('admin/seo-data','Admin\SeoDataController');

	Route::resource('admin/categories','Admin\CategoriesController');
	Route::resource('admin/products','Admin\ProductsController');

	Route::resource('admin/settings','Admin\SettingController');

});

app/Models/Faq.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Faq extends Model
{
    protected $table = 'faqs';
 	protected $primaryKey = 'id';

 	public function faq_detail(){
 		return $this->hasMany(FaqDetail::class,'faq_id');
 	}
}

app/Http/Controllers/Admin/FAQController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Faq;
use Illuminate\Support\Facades\Session;

class FAQController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $faq = Faq::paginate('20');
        return view('admin.pages.faq.index',compact('faq'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.pages.faq.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

           $request->validate([
                'question_category' => 'required',
                'status' => 'required'
            ], [
                'question_category.required' => 'Image is required',
                'statue.required' => 'Status is required'
            ]);
        $faq = new Faq();
        $faq->question_category = $request->question_category;
        $faq->status = $request->status;

        $faq->save();

         Session::flash('success','Record Updated successfully !'); 
        return redirect()->route('faq.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $faq = Faq::find($id);
        return view('admin.pages.faq.form',compact('faq'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $request->validate([
                'question_category' => 'required',
                'status' => 'required'
            ], [
                'question_category.required' => 'Image is required',
                'statue.required' => 'Status is required'
            ]);
        $faq = Faq::find($id);
        $faq->question_category = $request->question_category;
        $faq->status = $request->status;

        $faq->save();

        Session::flash('success','Record Updated successfully !');
        return redirect()->route('faq.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {  
        $faq = Faq::find($id);
        $faq->delete();
        Session::flash('info','Record Delete successfully !');
        return back();
    }
}

resources/views/admin/pages/faq/includes/create-form.blade.php
<style type="text/css">
   .col-form-label {
    padding-top: calc(.375rem + 1px);
    padding-bottom: calc(.375rem + 1px);
    margin-bottom: 0;
    font-size: inherit;
    line-height: 1.5;
    display: block;
    width: 100%;
    text-align: left !important;
 }
</style>
<div class="right_col" role="main" style="min-height: 942px;">
   <div class="">
      <div class="page-title">
         <div class="title_left">
            <h3>FAQ</h3>
         </div>
      </div>
      <div class="clearfix"></div>
      <div class="row">
         <div class="col-md-12 col-sm-12">
            <div class="x_panel">
               
               <div class="x_content">
                  @if(isset($faq) && !empty($faq))
                  
                  <form class="form-horizontal form-label-left" novalidate="" method="post" action="{{ route('faq.update',$faq->id) }}" enctype="multipart/form-data">
                     @method('PUT')
                  @else
                  <form class="form-horizontal form-label-left" novalidate="" method="post" action="{{ route('faq.store') }}" enctype="multipart/form-data">
                  
                  @endif
                     @csrf
                    
                     <span class="section">FAQ</span>
                     <div class="col-md-6 col-sm-6">   
                        <div class="item form-group bad">
                        <label class="col-form-label label-align" for="name">Question Category<span class="required">*</span>
                        </label>
                           <input id="question_category" class="form-control" data-validate-length-range="6" data-validate-words="2" name="question_category" placeholder="" required="" type="text" @if(isset($faq) && !empty($faq->question_category)) value="{{ $faq->question_category }}" @endif>
                        @if ($errors->has('question_category'))
                           <span class="text-danger">{{ $errors->first('question_category') }}</span>
                        @endif
                     </div>
                  </div>
                 
                  <div class="col-md-6 col-sm-6">
                     <div class="item form-group bad">
                        <label for="password" class="col-form-label label-align">Status</label>
                           <select class="custom-select" name="status" id="status">
                              <option value="">Please select status</option>
                              <option value="1">Active</option>
                              <option value="0">Inactive</option>
                           </select>
                           @if ($errors->has('status'))
                              <span class="text-danger">{{ $errors->first('status') }}</span>
                           @endif
                     </div>
                  </div>

                     <div class="ln_solid"></div>
                     <div class="form-group">
                        <div class="col-md-6 offset-md-3">
                           <button type="submit" class="btn btn-primary">Cancel</button>
                           <button id="send" type="submit" class="btn btn-success">
                              @if(isset($faq) && !empty($faq)) Update @else Submit @endif
                           </button>
                        </div>
                     </div>
                  </form>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>

resources/views/admin/pages/faq/includes/table.blade.php
<div class="right_col" role="main" style="min-height: 674px;">
   <div class="">
      <div class="page-title">
         <div class="title_left">
        
         </div>
         <div class="title_right">
            <div class="col-md-5 col-sm-5   form-group pull-right top_search">
               <div class="input-group">
                 <a href="{{ route('faq.create') }}" class="btn btn-primary">Add New Record</a>
               </div>
            </div>
         </div>
      </div>
      <div class="clearfix"></div>
      <div class="row" style="display: block;">
  
         <div class="col-md-12 col-sm-12  ">
            <div class="x_panel">
               <div class="x_title">
                  <h2>FAQ</h2>
                  <ul class="nav navbar-right panel_toolbox">
                     <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                     <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                           
                        </div>
                     </li>
                     <li><a class="close-link"><i class="fa fa-close"></i></a></li>
                  </ul>
                  <div class="clearfix"></div>
               </div>
               <div class="x_content">
                  
                  <div class="table-responsive">
                     <table class="table table-striped jambo_table bulk_action">
                        <thead>
                           <tr class="headings">
                              <th>
                                #
                              </th>
                              <th>question_category </th>
                              <th><span class="nobr">Status</span></th>
                              <th>
                                 Action
                              </th>
                           </tr>
                        </thead>
                        <tbody>
                           @if(isset($faq) && !empty($faq))
                           @foreach($faq as $key => $value)
                           <tr class="even pointer">
                              <td class="a-center ">
                                 {{ ++$key }}
                              </td>
                              
                              <td class=" ">{{ $value->question_category }}</td>
      
                              <td>
                                 {{ $value->status == 1 ? 'Active' : 'Inactive'  }}
                              </td>
                              <td>
                                 <a href="{{ route('faq.edit',$value->id) }}" class="btn btn-primary">Edit</a>
                                 <a class="delete btn btn-danger" href="javascript::void();" onclick="event.preventDefault();
                                                     document.getElementById('delete-faq-{{ $value->id }}').submit();">
                                                  Delete
                                 </a>
                                <form id="delete-faq-{{ $value->id }}" action="{{ route('faq.destroy',$value->id) }}" method="POST" style="display: none;">
                                 @method('delete')
                                        @csrf
                                </form>

                              </td>
                           </tr>
                           @endforeach
                           @endif
                        </tbody>
                     </table>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>