routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/','Website\HomeController@index')->name('home.index');
Route::get('/about-us','Website\HomeController@about')->name('about.us');
Route::get('/our-people','Website\HomeController@ourpeople')->name('our.people');
Route::get('/testimonial','Website\HomeController@testimonial')->name('testimonial');
Route::get('/faq','Website\HomeController@faq')->name('faq');
Route::get('/contact-us','Website\HomeController@contactus')->name('contact.us');

Route::get('/projects','Website\HomeController@projects')->name('projects');
Route::get('/project-detail/{name}/{id}','Website\HomeController@project_detail')->name('project.detail');
Route::get('/services','Website\HomeController@services')->name('services');
Route::get('/service-detail/{name}/{id}','Website\HomeController@service_detail')->name('service.detail');
Route::get('/news','Website\HomeController@news')->name('news');
Route::get('/news-detail','Website\HomeController@news_detail')->name('news.detail');

// products
Route::get('products','Website\HomeController@product_list')->name('products');
Route::get('products/{name}/{id}','Website\HomeController@product_bycat')->name('products.category');

Route::group(['middleware' => 'auth'], function(){
	// admin routes 
	Route::get('dashboard','Admin\DashboardController@index')->name('admin.dashboard');
	Route::resource('admin/home-image-slider','Admin\HomeImageSliderController');
	Route::resource('admin/offerforstudent','Admin\OfferForStudentController');
	Route::resource('admin/contactus','Admin\ContactUsController');
	Route::resource('admin/ourpresence','Admin\OurPresenceController');
	Route::resource('admin/awardsforyou','Admin\AwardsForYouController');
	Route::resource('admin/ourmindpower','Admin\OurMindPowerController');
	Route::resource('admin/ourpresence','Admin\OurPresenceController');
	Route::resource('admin/school','Admin\SchoolController');
	Route::resource('admin/testimonial','Admin\TestimonialController');
	Route::resource('admin/settings','Admin\WebsiteSettingController');
	Route::resource('admin/services','Admin\ServiceController');
	Route::resource('admin/service-detail','Admin\ServiceDetailController');
	Route::resource('admin/service-detail-image-slider','Admin\ServiceDetailImageSliderController');
	Route::resource('admin/what-we-make-us-different','Admin\WhatMakeUsDifferentController');
	Route::resource('admin/you-should-know','Admin\YouShouldKnowController');
	Route::resource('admin/projects','Admin\ProjectController');
	Route::resource('admin/project-detail','Admin\ProjectDetailController');
	Route::resource('admin/project-detail-image-slider','Admin\ProjectDetailImageSliderController');
	Route::resource('admin/faq','Admin\FAQController');
	Route::resource('admin/faq-detail','Admin\FAQDetailController');
	Route::resource('admin/aboutus','Admin\AboutusController');
	Route::resource('admin/aboutus-detail','Admin\AboutusDetailController');
	Route::resource('admin/what-we-do','Admin\WhatWeDoController');
	Route::resource('admin/what-we-do-detail','Admin\WhatWeDoDetailController');
	Route::resource('admin/our-team','Admin\OurTeamController');
	Route::resource('admin/general-info','Admin\GeneralInfoController');

	Route::resource('admin/seo-data','Admin\SeoDataController');

	Route::resource('admin/categories','Admin\CategoriesController');
	Route::resource('admin/products','Admin\ProductsController');

	Route::resource('admin/settings','Admin\SettingController');

});

app/Models/SeoData.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class SeoData extends Model
{
    
    protected $table = 'seo_data';
 	protected $primaryKey = 'id';
 	
}

app/Http/Controllers/Admin/SeoDataController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use App\Models\SeoData;


class SeoDataController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $seo_data = SeoData::paginate('20');
        return view('admin.pages.seo_data.index',compact('seo_data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.pages.seo_data.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {   
        // dd($request->all());

           $request->validate([
                'page_name' => 'required',
                'meta_title' => 'required',
                'meta_description' => 'required',
                'meta_canonical' => 'required',
                'meta_keywords' => 'required',
                'status' => 'required'
            ], [
                'meta_title.required' => 'Meta title is required',
                'meta_description.required' => 'Meta Description is required',
                'meta_canonical.required' => 'Nonfollow link tag is required',
                'page_name.required' => 'Image is required',
                'meta_keywords.required' => 'Meta Keywords is required',
                'statue.required' => 'Status is required'
            ]);
        $seo_data = new SeoData();
        $seo_data->meta_title = $request->meta_title;
        $seo_data->meta_description = $request->meta_description;
        $seo_data->meta_canonical = $request->meta_canonical;
        $seo_data->page_name = $request->page_name;
        $seo_data->meta_keywords = $request->meta_keywords;
        $seo_data->status = $request->status;

        $seo_data->save();

         Session::flash('success','Record Updated successfully !'); 
        return redirect()->route('seo-data.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $seo_data = SeoData::find($id);
        return view('admin.pages.seo_data.form',compact('seo_data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
          $request->validate([
                'page_name' => 'required',
                'meta_title' => 'required',
                'meta_description' => 'required',
                'meta_canonical' => 'required',
                'meta_keywords' => 'required',
                'status' => 'required'
            ], [
                'meta_title.required' => 'Meta title is required',
                'meta_description.required' => 'Meta Description is required',
                'meta_canonical.required' => 'Nonfollow link tag is required',
                'page_name.required' => 'Image is required',
                'meta_keywords.required' => 'Meta Keywords is required',
                'statue.required' => 'Status is required'
            ]);
        $seo_data = SeoData::find($id);
        $seo_data->meta_title = $request->meta_title;
        $seo_data->meta_description = $request->meta_description;
        $seo_data->meta_canonical = $request->meta_canonical;
        $seo_data->page_name = $request->page_name;
        $seo_data->meta_keywords = $request->meta_keywords;
        $seo_data->status = $request->status;

        $seo_data->save();

        Session::flash('success','Record Updated successfully !');
        return redirect()->route('seo-data.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {  
        $seo_data = SeoData::find($id);
        if(!is_null($seo_data)){
            $file_path = public_path('uploads/seo_data' . DIRECTORY_SEPARATOR . $seo_data->image_alt_tag);
            if (is_file($file_path)) {
                unlink($file_path);
            }
        }
        $seo_data->delete();
        Session::flash('info','Record Delete successfully !');
        return back();
    }
}

resources/views/admin/pages/seo_data/includes/create-form.blade.php
<style type="text/css">
   .col-form-label {
    padding-top: calc(.375rem + 1px);
    padding-bottom: calc(.375rem + 1px);
    margin-bottom: 0;
    font-size: inherit;
    line-height: 1.5;
    display: block;
    width: 100%;
    text-align: left !important;
 }
</style>
<div class="right_col" role="main" style="min-height: 942px;">
   <div class="">
      <div class="page-title">
         <div class="title_left">
            <h3>Seo Data</h3>
         </div>
      </div>
      <div class="clearfix"></div>
      <div class="row">
         <div class="col-md-12 col-sm-12">
            <div class="x_panel">
               
               <div class="x_content">
                  @if(isset($seo_data) && !empty($seo_data))
                  
                  <form class="form-horizontal form-label-left" novalidate="" method="post" action="{{ route('seo-data.update',$seo_data->id) }}" enctype="multipart/form-data">
                     @method('PUT')
                  @else
                  <form class="form-horizontal form-label-left" novalidate="" method="post" action="{{ route('seo-data.store') }}" enctype="multipart/form-data">
                  
                  @endif
                     @csrf
                     
                     <span class="section">Seo Data </span>

                     <div class="col-md-6 col-sm-6">
                        <div class="item form-group bad">
                           <label for="password" class="col-form-label label-align">Page Name</label>
                              <select class="custom-select" name="page_name" id="page_name">
                                 <option value="">Select Page Name</option>
                                 <option value="home_page">Home </option>
                                 <option value="about_us_page">About Us </option>
                                 <option value="our_team_page"> Our Team Page </option>
                                 <option value="testimonial_page"> Testimonial Page </option>
                                 <option value="faq_page"> Faq Page </option>
                                 <option value="contact_page"> Contact Page </option>
                                 <option value="all_projects"> All Projects Page </option>
                                 @if(!is_null(projects()))
                                 @foreach(projects() as $key => $value)
                                 @php
                                    $page_name = str_replace(' ', '_', $value->title);
                                 @endphp
                                    <option value="{{ $page_name }}_page"> {{ $value->title }} </option>
                                 @endforeach
                                 @endif
                                 <option value="all_services_page"> All Services Page </option>
                                 @if(!is_null(services()))
                                 @foreach(services() as $key => $value)
                                 @php
                                    $page_name = str_replace(' ', '_', $value->heading);
                                 @endphp
                                    <option value="{{ $page_name }}_page"> {{ $value->heading }} </option>
                                 @endforeach
                                 @endif
                              </select>
                              @if ($errors->has('status'))
                                 <span class="text-danger">{{ $errors->first('status') }}</span>
                              @endif
                        </div>
                     </div>

                     <div class="col-md-6 col-sm-6">   
                        <div class="item form-group bad">
                        <label class="col-form-label label-align" for="name">Title<span class="required">*</span>
                        </label>
                           <input id="meta_title" class="form-control"  name="meta_title" placeholder="" required="" type="text" @if(isset($seo_data) && !empty($seo_data->meta_title)) value="{{ $seo_data->meta_title }}" @endif>
                        @if ($errors->has('meta_title'))
                           <span class="text-danger">{{ $errors->first('meta_title') }}</span>
                        @endif
                     </div>
                  </div>

                     <div class="col-md-6 col-sm-6">
                        <div class="item form-group bad">
                           <label class="col-form-label label-align" for="email"> Meta Description<span class="required">*</span>
                           </label>
                              <input type="text" id="meta_description" name="meta_description" required="" class="form-control" @if(isset($seo_data) && !empty($seo_data->meta_description)) value="{{ $seo_data->meta_description }}" @endif>
                           @if ($errors->has('meta_description'))
                              <span class="text-danger">{{ $errors->first('meta_description') }}</span>
                           @endif
                        </div>
                     </div>
                     <div class="col-md-6 col-sm-6">
                        <div class="item form-group bad">
                           <label class="col-form-label label-align" for="email"> Meta Keywords <span class="required">*</span>
                           </label>
                              <input type="text" id="meta_keywords" name="meta_keywords" required="" class="form-control" @if(isset($seo_data) && !empty($seo_data->meta_keywords)) value="{{ $seo_data->meta_keywords }}" @endif>
                           @if ($errors->has('meta_keywords'))
                              <span class="text-danger">{{ $errors->first('meta_keywords') }}</span>
                           @endif
                        </div>
                     </div>

                   
                     <div class="col-md-6 col-sm-6">
                        <div class="item form-group bad">
                           <label class="col-form-label label-align" for="email"> Canonical Tag Page URl <span class="required">*</span>
                           </label>
                              <input type="text" id="meta_canonical" name="meta_canonical" required="" class="form-control" @if(isset($seo_data) && !empty($seo_data->meta_canonical)) value="{{ $seo_data->meta_canonical }}" @endif>
                           @if ($errors->has('meta_canonical'))
                              <span class="text-danger">{{ $errors->first('meta_canonical') }}</span>
                           @endif
                        </div>
                     </div>
         

      
                  <div class="col-md-6 col-sm-6">
                     <div class="item form-group bad">
                        <label for="password" class="col-form-label label-align">Status</label>
                           <select class="custom-select" name="status" id="status">
                              <option value="">Please select status</option>
                              <option value="1">Active</option>
                              <option value="0">Inactive</option>
                           </select>
                           @if ($errors->has('status'))
                              <span class="text-danger">{{ $errors->first('status') }}</span>
                           @endif
                     </div>
                  </div>

                     <div class="ln_solid"></div>
                     <div class="form-group">
                        <div class="col-md-6 offset-md-3">
                           <button type="submit" class="btn btn-primary">Cancel</button>
                           <button id="send" type="submit" class="btn btn-success">
                              @if(isset($seo_data) && !empty($seo_data)) Update @else Submit @endif
                           </button>
                        </div>
                     </div>
                  </form>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>

resources/views/admin/pages/seo_data/includes/table.blade.php
<div class="right_col" role="main" style="min-height: 674px;">
   <div class="">
      <div class="page-title">
         <div class="title_left">
         </div>
         <div class="title_right">
            <div class="col-md-5 col-sm-5   form-group pull-right top_search">
               <div class="input-group">
                 <a href="{{ route('seo-data.create') }}" class="btn btn-primary">Add New Record</a>
               </div>
            </div>
         </div>
      </div>
      <div class="clearfix"></div>
      <div class="row" style="display: block;">
  
         <div class="col-md-12 col-sm-12  ">
            <div class="x_panel">
               <div class="x_title">
                  <h2>Seo Data</h2>
                  <ul class="nav navbar-right panel_toolbox">
                     <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a></li>
                     <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                          
                        </div>
                     </li>
                     <li><a class="close-link"><i class="fa fa-close"></i></a></li>
                  </ul>
                  <div class="clearfix"></div>
               </div>
               <div class="x_content">
                  
                  <div class="table-responsive">
                     <table class="table table-striped jambo_table bulk_action">
                        <thead>
                           <tr class="headings">
                              <th>
                                #
                              </th>
                              <th>Title </th>
                              <th>Meta Description</th>
                              <th> Meta Keywords </th>
                              <th> Canonical Tag </th>
                              <th> Page Name </th>
                              <th>Status</th>
                              <th>
                                 Action
                              </th>
                           </tr>
                        </thead>
                        <tbody>
                           @if(isset($seo_data) && !empty($seo_data))
                           @foreach($seo_data as $key => $value)
                           <tr>
                              <td>
                                 {{ ++$key }}
                              </td>
                              
                              <td> {{ $value->meta_title }} </td>
                              <td> {{ $value->meta_description }} </td>
                              <td> {{ $value->meta_keywords }} </td>
                              <td> {{ $value->meta_canonical }} </td>
                              @php
                                 $page_name = str_replace('_', ' ', $value->page_name);
                              @endphp
                              <td> {{ $page_name }} </td>
                              <td>
                                 {{ $value->status == 1 ? 'Active' : 'Inactive'  }}
                              </td>
                              <td>
                                 <a href="{{ route('seo-data.edit',$value->id) }}" class="btn btn-primary">Edit</a>
                                 <a class="delete btn btn-danger" href="javascript::void();" onclick="event.preventDefault();
                                                     document.getElementById('delete-seo-data-{{ $value->id }}').submit();">
                                                  Delete
                                 </a>
                                <form id="delete-seo-data-{{ $value->id }}" action="{{ route('seo-data.destroy',$value->id) }}" method="POST" style="display: none;">
                                 @method('delete')
                                        @csrf
                                </form>

                              </td>
                           </tr>
                           @endforeach
                           @endif
                        </tbody>
                     </table>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>